import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Navbar from '../components/Navbar/navbar'
import DownArrow from '../components/DownArrow/downArrow'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="author" content="MDIA 2109"/>
        <meta property="og:title" content='Assignment #1 - Home Page'/>
        <meta property="og:description" content='BCIT Digital Design and Development Diploma'/>
        <link rel="icon" href="/favicon.png" />
      </Head>
      <main className={styles.main}>
        <Navbar/>
        <div className={styles.body}>
          <h1>An investment in knowledge pays the best interest.</h1>
          <div className={styles.divider}></div>
          <p className={styles.para}>Different than a college or university, the British Columbia Institute of Technology offers practical, flexible, applied education with instructors who have direct, hands-on experience in their field.</p>
          <div className={styles.buttonContainer}>
            <a href="/about"><button className={styles.button}>More About Us</button></a>
            <a href="/contact"><button className={styles.button}>Contact Us</button></a>
          </div>
        </div>
        <div className={styles.arrow}>
        <a href='/about'><DownArrow/></a>
        </div>
      </main>
    </>
  )
}
